// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTicket struct {
	Type   string `json:"type"`
	Status bool   `json:"status"`
}

// GraphQl schema defines the data requirements that clients can request from the GraphQL API
type Ticket struct {
	ID        string `json:"id"`
	Type      string `json:"type"`
	Status    bool   `json:"status"`
	CreatedAt string `json:"createdAt"`
	User      *User  `json:"user"`
}

// User is a type of person that uses our app
type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
